# Generated by Django 5.2.17 on 2026-09-18 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='booking_type',
            field=models.CharField(choices=[('hotel', 'Hotel'), ('restaurant', 'Restaurant'), ('activity', 'Activity'), ('taxi', 'Taxi'), ('place', 'Place')], max_length=20),
        ),
    ]
